language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

before_script:
  - travis_retry composer install --no-interaction

script:
  - bin/test.sh

